name: Java Checkout
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: javac LoadingBar.java
  bearer:
    runs-on: ubuntu-latest
    container:
      image: bearer/bearer:latest-amd64
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Scan
      run: bearer scan .
  
