name: Java
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: javac LoadingBar.java
  bearer:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: bearer/bearer:latest-amd64
    env:
      GITHUB_WORKSPACE: "/tmp/scan"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Scan
      run: bearer scan /tmp/scan
  
