name: Main_Pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: javac LoadingBar.java
