name: pipeline
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**/README.md'

jobs:
  check-bash:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Shellcheck
      uses: ConorMacBride/install-package@v1
      with:
        apt: shellcheck
    - name: Syntax check the Bash version
      run: shellcheck $GITHUB_WORKSPACE/loading_bar.sh
  check-java:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: javac LoadingBar.java
  check-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Syntax Check
      run: python3 -m py_compile loadingBar.py
  bearer:
    needs: [check-java, check-python]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Bearer
      run: curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
    - name: Run Scan
      run: ./bin/bearer scan $GITHUB_WORKSPACE --report security --output report.json
    - name: Save Report to Artifact
      uses: actions/upload-artifact@v3
      with:
        name: bearer-report
        path: ./report.json
  
