name: pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: javac LoadingBar.java
  bearer:
    needs: build-java
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Bearer
      run: curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh
    - name: Run Scan
      run: ./bin/bearer scan $GITHUB_WORKSPACE --report security --output report.json
    - name: Save Report to Artifact
      uses: actions/upload-artifact@v3
      with:
        name: bearer-report
        path: ./report.json
  
